[tool.poetry]
name = "pythonproject3"
version = "0.1.0"
description = ""
authors = ["mary free student <masha1207355@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
